Support: CMS Modules
terraform-ibm-modules/terraform-ibm-certificate-manager pull request #1
Opened 2020-10-20 10:51 UTC by kavya498

2020-11-02 06:43 UTC, umarali-nagoor requested changes

2020-11-02 06:43 UTC, umarali-nagoor commented on README.md
> +This module is meant for use with Terraform 0.12. If you haven't
Remove sentences related 11 support.

2020-11-02 06:43 UTC, umarali-nagoor commented on README.md
> +data "ibm_certificate_manager_certificates" "certs"{
Lets capture module related example, should be sufficient.

2020-11-02 06:43 UTC, umarali-nagoor commented on modules/ibm-cms-instance/main.tf
> +
Can we capture even "parameters" argument which is optional

2020-11-02 06:43 UTC, umarali-nagoor commented on modules/ibm-cms-instance/provider.tf
> +# IBM Cloud certificate manager Provisioning, Import and order Certificates
Can we have this provider block on examples side

2020-11-02 06:43 UTC, umarali-nagoor commented on modules/ibm-cms-order/main.tf
> +  description                     = (var.description != null ? var.description : null)
Make argument names are inline with respective UI variaible names

2020-11-02 06:43 UTC, umarali-nagoor commented on modules/ibm-cms-order/main.tf
> +  domain_validation_method        = var.domain_validation_method
Can we have null check for all optional fields like domain_validation_method, dns_provider_instance_crn and etc

2020-11-02 06:43 UTC, umarali-nagoor commented on modules/ibm-cms-order/provider.tf
> +# IBM Cloud certificate manager Provisioning, Import and order Certificates
Shift provider block to example

2020-11-02 06:43 UTC, umarali-nagoor commented on modules/ibm-cms-order/variables.tf
> +############################################################################
Have default value as null for all optional fields

2020-11-02 06:43 UTC, umarali-nagoor commented on modules/ibm-cms-import/provider.tf
> +############################################################################
Shift provider block to examples

2020-11-02 06:43 UTC, umarali-nagoor commented on modules/ibm-cms-import/variables.tf
> +variable "description" {
Assign null value as default to all optional arguments

2020-11-02 06:43 UTC, umarali-nagoor commented on examples/ibm-cms-instance/main.tf
> +  tags              = (var.tags != null ? var.tags : null)
Lets have all null checks on modules side, in examples user just configures the values

2020-11-02 06:43 UTC, umarali-nagoor commented on examples/ibm-cms-order/main.tf
> +  description                     = (var.description != null ? var.description : null)
Lets shift all null checks to module end

2020-11-02 06:43 UTC, umarali-nagoor commented on examples/ibm-cms-order/README.md
> +  description                     = (var.description != null ? var.description : null)
Remove null checks in example

2020-11-02 06:43 UTC, umarali-nagoor commented on examples/ibm-cms-import/import-from-file/main.tf
> +  description                     = (var.description != null ? var.description : null)
Shift the null check to module level

2020-11-05 06:09 UTC, kavya498 commented on README.md
> +data "ibm_certificate_manager_certificates" "certs"{
Thought it would be easy access to user if the datasources for resources related module are mentioned..

2020-11-05 06:13 UTC, kavya498 commented on modules/ibm-cms-order/main.tf
> +  domain_validation_method        = var.domain_validation_method
dns_provider_instance_crn is required parameter

2020-11-05 06:14 UTC, kavya498 commented on modules/ibm-cms-order/main.tf
> +  domain_validation_method        = var.domain_validation_method
provided null check for domain_validation_method

2020-11-05 06:16 UTC, kavya498 commented on modules/ibm-cms-order/variables.tf
> +############################################################################
done

2020-11-05 06:16 UTC, kavya498 commented on modules/ibm-cms-import/variables.tf
> +variable "description" {
done

2020-11-05 06:16 UTC, kavya498 commented on examples/ibm-cms-instance/main.tf
> +  tags              = (var.tags != null ? var.tags : null)
done

2020-11-05 06:17 UTC, kavya498 commented on examples/ibm-cms-order/README.md
> +  description                     = (var.description != null ? var.description : null)
done

2020-11-05 06:17 UTC, kavya498 commented on examples/ibm-cms-import/import-from-file/main.tf
> +  description                     = (var.description != null ? var.description : null)
done

2020-11-05 06:17 UTC, kavya498 commented on modules/ibm-cms-order/main.tf
> +  description                     = (var.description != null ? var.description : null)
all the arguments are inline with UI

2020-11-05 06:20 UTC, kavya498 commented on modules/ibm-cms-instance/provider.tf
> +# IBM Cloud certificate manager Provisioning, Import and order Certificates
As per discussion with Harini, we can have provider block in  both examples and module level..

2020-11-05 06:20 UTC, kavya498 commented on modules/ibm-cms-order/provider.tf
> +# IBM Cloud certificate manager Provisioning, Import and order Certificates
As per discussion with Harini, we can have provider block in  both examples and module level..

2020-11-05 06:21 UTC, kavya498 commented on examples/ibm-cms-order/main.tf
> +  description                     = (var.description != null ? var.description : null)
done

2020-11-05 06:21 UTC, kavya498 commented on modules/ibm-cms-import/provider.tf
> +############################################################################
As per discussion with Harini, we can have provider block in  both examples and module level..

2020-11-20 05:09 UTC, merged